language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests tests.unit
deploy:
  provider: pypi
  password:
    secure: fVFQor29VlzO4RddQZRhG/N7rJYKyb17v4pvIZndsmECblsU68xiiGJFnUxqNix1HFnU+d5bxDYG8abgAC0mJZvZoNtRXGPZzldytAZJ2nII30g47Wgf3yGQBDs4MFnTKR7NuGbU4aqCX9Sypp9C+p8bT7EWyvYeGBSh0OGkhUpDdMB0TbK/PLFuaLsva2oe0swbvgCP0pomBu6wpcq+K1kdp3BBt+G/CRKOP/6Wej1bHNrJ4hmdRs3JluP/ql3QV6oCGdIyG+VtdDgEqqhIrPfoZYtioYvVRFUIWcm6+gt7rZ6J3w2umRmwwZrMvi7Z88whvLzYaIG+HH6SwuGYfPmb3frGzWDDCoXExlMOHUT9wQ+fPh1ySHLupmVR1VFs7DEjfWDHWkj4c7SU2B2sRGVZ55oXYjnxjDRbX0Rirm4P/5ClfuYIe5b+2ps+DxYaMuPotZBlSqHVKfEEdNxJ0X+LKXt0Rvj7fOD7z8dktFsF27UmKiB1SbbUPCt4lMa7+dNa8Qy3oV0vIONOn0151fUrUUTcFoa+uR8lb13u46lLwWjp6p6vLyPMG05J+J99Q0TrDAjxAutI4+u3iuXC9UCmljMPUe7AX86w3IaBMfNri/lXi0psng3LO3o87qINuKCYgMoJnzAhaanqEy/E8HxaswSqrpLIYet2R/NzYlw=
  user:
    secure: NGd74JUr6wx6Pae9ihN2gBJgE5WgurvS8vnpdjw+Z8SnKqG25piM/CQrtCPws4Fi9k1lbawnGqOud6mQLiYUxT06SM9+VkNjRoKCCEFBsXTTsyAd3nNLtBAwzabPvUc7N4SGdfHf6FqM+S4UlrcVNhQEIOzCW9jkziMolZKHA2UdbFhZnd6CprvcJm6zAkXTpLgyNCG3TN3qbXEqWzZchBLPSLutZP9VtAgrPc//1nobHu+jHyWznHp1XjUOb+dhYEPpmNN4LAC3CbQx/c2nCbEXENFMh5BPnf21LYIiFAdO6zZ0ghBi6AR5zSCU2P5tCa0nCAGqdu1OBEz8Q5F5lC3mj3QPPlXmQk0WIWwJMpZErmreqRK8gsqD0vxwn3VEnXoq2eDVHvOypkVtuOtK1+mYHUwM/1fJ32R6gkPpJbg0X3E2Nc0XJGw5xhtznwR2nZI618eqPgpzcNoj28epx+dMLyNB5qwDQlmlzE37lAfLlpAREIYrc6mz3MJYrWUzPvUPQuS/fayxDwNz9dzFGuoXNLx7hZtTLdwkN5Wwz39oO4iieiPGKkXrjzcjnpGjQbSzBqUIcXJW6LN7VL8P/dbtI4BTSNnCChBK9/LziME5fUJkX8KHLJ1aIoO4EVas2BrQwErr0FMBTb7egY7ckX79psJyCkD5TvLg/Vc30eI=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: VZ+1ScbK5Mio+XdZzOIyyNO2G+PL7SJZ8z/aVf6JaC86PZL7dBLGELgsAFNOvel0g9mBQ2Gt9s45BvfUR3fN/EFA//Gr61k2999tnpi62J2qL2yBRJWqSD+sYEo7Od99/6lL/A1Tq2+GzH64c1usZR78rXRj2v7ioVtOB1q/Yuj8JSNba3mb2VppDc2kMv+mRPn7y19h/XDdAJiuaSVDd3Wq1EFhDWgkglcx8Z4XDygSxGOUFgjTIvivjqLsCgm0dkoyHBoV2lSgZ1WvaeQqXNZk5pE1YI1nMmPstcbC94+I49BrxpWycx8z83L3nQxQw0gqDqLB3P2obfS2TXXyuFrRRG/SMp4AMZ61A2EftU1t6osCLXmerBgOJYhyNOWT3spExm/znfzu4vFCJMVbHjMsAAhQDy/TYMQfv1DV4qHzZYOHC03ozBWHlP/1Kd6eJcjfSYKOIACXvqG2M04/QQxsysKISF3LphY11ZpDKOX81ZPcsNOI5PQlKwfxvCzqwFCMsEUO9dRhCG7ZmJbJ25w9dNXjfCtO/s5g00mNQM8GHcRvH8gf7XLHRkrqMQGTyeJkTX1cYbVPdZAEfldlv05HSNb1lMafgcFAkRwdHkdSZT5evocM8Mz6iXC/UA2Z6zlL358oBmhDTFLGTAoKYFxAukTw9GYUjlz1MKlF/9g=
