language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests tests.unit
deploy:
  provider: pypi
  password:
    secure: fVFQor29VlzO4RddQZRhG/N7rJYKyb17v4pvIZndsmECblsU68xiiGJFnUxqNix1HFnU+d5bxDYG8abgAC0mJZvZoNtRXGPZzldytAZJ2nII30g47Wgf3yGQBDs4MFnTKR7NuGbU4aqCX9Sypp9C+p8bT7EWyvYeGBSh0OGkhUpDdMB0TbK/PLFuaLsva2oe0swbvgCP0pomBu6wpcq+K1kdp3BBt+G/CRKOP/6Wej1bHNrJ4hmdRs3JluP/ql3QV6oCGdIyG+VtdDgEqqhIrPfoZYtioYvVRFUIWcm6+gt7rZ6J3w2umRmwwZrMvi7Z88whvLzYaIG+HH6SwuGYfPmb3frGzWDDCoXExlMOHUT9wQ+fPh1ySHLupmVR1VFs7DEjfWDHWkj4c7SU2B2sRGVZ55oXYjnxjDRbX0Rirm4P/5ClfuYIe5b+2ps+DxYaMuPotZBlSqHVKfEEdNxJ0X+LKXt0Rvj7fOD7z8dktFsF27UmKiB1SbbUPCt4lMa7+dNa8Qy3oV0vIONOn0151fUrUUTcFoa+uR8lb13u46lLwWjp6p6vLyPMG05J+J99Q0TrDAjxAutI4+u3iuXC9UCmljMPUe7AX86w3IaBMfNri/lXi0psng3LO3o87qINuKCYgMoJnzAhaanqEy/E8HxaswSqrpLIYet2R/NzYlw=
  user:
    secure: NGd74JUr6wx6Pae9ihN2gBJgE5WgurvS8vnpdjw+Z8SnKqG25piM/CQrtCPws4Fi9k1lbawnGqOud6mQLiYUxT06SM9+VkNjRoKCCEFBsXTTsyAd3nNLtBAwzabPvUc7N4SGdfHf6FqM+S4UlrcVNhQEIOzCW9jkziMolZKHA2UdbFhZnd6CprvcJm6zAkXTpLgyNCG3TN3qbXEqWzZchBLPSLutZP9VtAgrPc//1nobHu+jHyWznHp1XjUOb+dhYEPpmNN4LAC3CbQx/c2nCbEXENFMh5BPnf21LYIiFAdO6zZ0ghBi6AR5zSCU2P5tCa0nCAGqdu1OBEz8Q5F5lC3mj3QPPlXmQk0WIWwJMpZErmreqRK8gsqD0vxwn3VEnXoq2eDVHvOypkVtuOtK1+mYHUwM/1fJ32R6gkPpJbg0X3E2Nc0XJGw5xhtznwR2nZI618eqPgpzcNoj28epx+dMLyNB5qwDQlmlzE37lAfLlpAREIYrc6mz3MJYrWUzPvUPQuS/fayxDwNz9dzFGuoXNLx7hZtTLdwkN5Wwz39oO4iieiPGKkXrjzcjnpGjQbSzBqUIcXJW6LN7VL8P/dbtI4BTSNnCChBK9/LziME5fUJkX8KHLJ1aIoO4EVas2BrQwErr0FMBTb7egY7ckX79psJyCkD5TvLg/Vc30eI=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: xWWAsxqgN3oO5vsWEMrCU2aaMsGta2Fz2afJWW+MTyry/3L1oxmGM1wHblH6HSuDnWGnPx+or5UqyqmNQxi5hc0bd84r2228arMTXTcWfzX8l6JvE1rANTgmx/xylFxlf/C2Fmgos60LlqniqC2Bsvq8fH9E9KMHTv/RuI02K490hlUiZx1Ttq8IgJbSu1qSYRLBq5UZ6SjpeencYy+DaApgy3FAQdN13wkyowobmzP14B+zG7mgrvP4oxNtNPoUDw7y1z2yHXHykIj2DYP1agpfWn/hquE1pPeYLgqOTnnWmYL6dXSYHM3IIg9cWDYKvO8bljMrqNWXOtWzAYIKTb8+8ExosyJ+DX4/mXZ6PJMXxMH8YsQxDl3h/qjnVGKjnpqKpHTiepmQ+J3pKUJV5HY+WbmQ7jR43mYSLuHczPmZAUERGb1g/C2ehFOyp9MYDf57e5Hx44JiF1G2bDfkRCmlHqxtgJb4KAAt9jBDqTCDMfFeJqBy3LOzRFlKq0/RNJRXoYr3vK0IWTmIUc2mgjgcQWaNc/xMv8Acl8uGaIVJxlzJ3vip+l+zA38wpJHygX6V8CBSPduv2q02tvvM4na2SlPMuNMyyjURgjV1IV0yYXBHv+HpXmdElXDCRtw2hJflPi480LOb9Pz/nYN3nlPFu442FFcTnKL15gc6oJg=
