language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests tests.unit
deploy:
  password:
    secure: 38bBKlgTvc3Y/DchU8trpkdrzdRSCFiE7Nk+egkZGRN6xT4M2k4m4I75p6aQ4tCk7r0uMnpzL1ZT1uMAMoUDhv7AFnM0EEdgit7rwNYghGEZO8Dv5LNkOWO7jH+1NhRPdeUgCjHnR6pmiaJVjvxwQxTC8WVeAf/Y/XKRlvSt7/hkXG8FH1WXJ06Rzs0huItYQn8jMhC7L1NPlMaBKfXHPdgY9RRm+9WokvaoIaG6r51hbqt6CgpYJKq7TRRU/Bu8A836nDj2MyJjtaIdv4he2XT//92AQVe+P/ROOBvuMePZzN4ZoSHz6WGz9H993egV5dDxZGAvpPMOfAgPv2egkBDELInOQQY+Q7zOmUoweyzCPaLdcWylaMLQhq5gulzrrLQFJKnVQiiMemrzrGafT6lv4KiC8mL7mzlD0MDYAsqUvtq5i7pk17DTC2GlhsBt7yNl2MextVsJMF5zcfmfZVhuLBt8sCL1i+3Iar3Vt2WgCW8+HYKB81E+7FIVrLphhSibOpdCU70TdHHPXOXEzXaqx1aFEogtn8kAniVNc7fCCCNVtrEEt8pq4GPEsFJA46eK4vkXSpJQd4B6GAyVckEiqx4Grwt06CiC60BOWQUhlAbIqmLXyGrDQkF08p24Ga0NfEAJr35sfhr1sJ01dUnBshDraH3Izc+LSHdeCts=
notifications:
  hipchat:
    rooms:
      secure: VZ+1ScbK5Mio+XdZzOIyyNO2G+PL7SJZ8z/aVf6JaC86PZL7dBLGELgsAFNOvel0g9mBQ2Gt9s45BvfUR3fN/EFA//Gr61k2999tnpi62J2qL2yBRJWqSD+sYEo7Od99/6lL/A1Tq2+GzH64c1usZR78rXRj2v7ioVtOB1q/Yuj8JSNba3mb2VppDc2kMv+mRPn7y19h/XDdAJiuaSVDd3Wq1EFhDWgkglcx8Z4XDygSxGOUFgjTIvivjqLsCgm0dkoyHBoV2lSgZ1WvaeQqXNZk5pE1YI1nMmPstcbC94+I49BrxpWycx8z83L3nQxQw0gqDqLB3P2obfS2TXXyuFrRRG/SMp4AMZ61A2EftU1t6osCLXmerBgOJYhyNOWT3spExm/znfzu4vFCJMVbHjMsAAhQDy/TYMQfv1DV4qHzZYOHC03ozBWHlP/1Kd6eJcjfSYKOIACXvqG2M04/QQxsysKISF3LphY11ZpDKOX81ZPcsNOI5PQlKwfxvCzqwFCMsEUO9dRhCG7ZmJbJ25w9dNXjfCtO/s5g00mNQM8GHcRvH8gf7XLHRkrqMQGTyeJkTX1cYbVPdZAEfldlv05HSNb1lMafgcFAkRwdHkdSZT5evocM8Mz6iXC/UA2Z6zlL358oBmhDTFLGTAoKYFxAukTw9GYUjlz1MKlF/9g=
